### PR TITLE
Bug/#13 fix cmd on macos

### LINKED ISSUE #13: Lights Off doesn't seem to be doing anything on Mac OS X
Hi there, Lights off doesn't seem to be working here. Mac OS X 10.14.6, Rack 1.1.6. Tried using the shortcut  and manually changing the dimness, to no avail.

### PR DESCRIPTION
**Pull request by stoermelder**

### CODE REVIEW

File: src/LightsOff.cpp [hunk 1]
```diff
@@ -182,7 +183,7 @@ struct LightsOffWidget : ModuleWidget {
 		};
 
 		menu->addChild(new MenuSeparator());
-		menu->addChild(construct<MenuLabel>(&MenuLabel::text, "Hotkey Ctrl/Cmd+Alt+X"));
+		menu->addChild(construct<MenuLabel>(&MenuLabel::text, string::f("Hotkey %s+Alt+X", RACK_MOD_CTRL_NAME)));
```
Comment (david-c14) [inline src/LightsOff.cpp]: You could avoid the `string::f` entirely
the pre-processor concatenates raw adjacent string literals so you can just do:
`"Hotkey " RACK_MOD_CTRL_NAME "+Alt+X"`

see phase 6 of [translation phases](https://en.cppreference.com/w/cpp/language/translation_phases)

Comment (david-c14) [reply src/LightsOff.cpp]: Let me be clear.  This module is your code and I don't want to dictate how it's written.
As far as I'm concerned you can merge your own pull requests if you want.
I made you a collaborator because this is Omri's project and not mine.

Comment (david-c14) [reply src/LightsOff.cpp]: But I'm happy to keep reviewing PRs if you want.

Comment (stoermelder) [reply src/LightsOff.cpp]: Thanks for pulling this in, David. I'm aware I can do it myself and I will do so, it was just a matter of time and priority during the last month.
